version: '3.9'

services:
  webapp:
    build:
      context: ./webapp
    container_name: webapp
    volumes:
      - ./webapp:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build:
      context: ./webapp
    container_name: celery
    command: celery -A webapp.celery worker --loglevel=info
    volumes:
      - ./webapp:/app
    depends_on:
      - redis
      - postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
    networks:
      - app_network

  celery-beat:
    build:
      context: ./webapp
    container_name: celery-beat
    command: celery -A webapp.celery beat --loglevel=info
    volumes:
      - ./webapp:/app
    depends_on:
      - redis
      - postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
